# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1334/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1334/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fett/repos/comp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fett/repos/comp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1334/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1334/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fett/repos/comp/CMakeFiles /home/fett/repos/comp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fett/repos/comp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gpu_elementstuffing

# Build rule for target.
gpu_elementstuffing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpu_elementstuffing
.PHONY : gpu_elementstuffing

# fast build rule for target.
gpu_elementstuffing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/build
.PHONY : gpu_elementstuffing/fast

src/benchs/bench_binary_op_baseline.o: src/benchs/bench_binary_op_baseline.cu.o
.PHONY : src/benchs/bench_binary_op_baseline.o

# target to build an object file
src/benchs/bench_binary_op_baseline.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_binary_op_baseline.cu.o
.PHONY : src/benchs/bench_binary_op_baseline.cu.o

src/benchs/bench_binary_op_baseline.i: src/benchs/bench_binary_op_baseline.cu.i
.PHONY : src/benchs/bench_binary_op_baseline.i

# target to preprocess a source file
src/benchs/bench_binary_op_baseline.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_binary_op_baseline.cu.i
.PHONY : src/benchs/bench_binary_op_baseline.cu.i

src/benchs/bench_binary_op_baseline.s: src/benchs/bench_binary_op_baseline.cu.s
.PHONY : src/benchs/bench_binary_op_baseline.s

# target to generate assembly for a file
src/benchs/bench_binary_op_baseline.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_binary_op_baseline.cu.s
.PHONY : src/benchs/bench_binary_op_baseline.cu.s

src/benchs/bench_binary_op_nogaps.o: src/benchs/bench_binary_op_nogaps.cu.o
.PHONY : src/benchs/bench_binary_op_nogaps.o

# target to build an object file
src/benchs/bench_binary_op_nogaps.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_binary_op_nogaps.cu.o
.PHONY : src/benchs/bench_binary_op_nogaps.cu.o

src/benchs/bench_binary_op_nogaps.i: src/benchs/bench_binary_op_nogaps.cu.i
.PHONY : src/benchs/bench_binary_op_nogaps.i

# target to preprocess a source file
src/benchs/bench_binary_op_nogaps.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_binary_op_nogaps.cu.i
.PHONY : src/benchs/bench_binary_op_nogaps.cu.i

src/benchs/bench_binary_op_nogaps.s: src/benchs/bench_binary_op_nogaps.cu.s
.PHONY : src/benchs/bench_binary_op_nogaps.s

# target to generate assembly for a file
src/benchs/bench_binary_op_nogaps.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_binary_op_nogaps.cu.s
.PHONY : src/benchs/bench_binary_op_nogaps.cu.s

src/benchs/bench_binary_op_slabs.o: src/benchs/bench_binary_op_slabs.cu.o
.PHONY : src/benchs/bench_binary_op_slabs.o

# target to build an object file
src/benchs/bench_binary_op_slabs.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_binary_op_slabs.cu.o
.PHONY : src/benchs/bench_binary_op_slabs.cu.o

src/benchs/bench_binary_op_slabs.i: src/benchs/bench_binary_op_slabs.cu.i
.PHONY : src/benchs/bench_binary_op_slabs.i

# target to preprocess a source file
src/benchs/bench_binary_op_slabs.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_binary_op_slabs.cu.i
.PHONY : src/benchs/bench_binary_op_slabs.cu.i

src/benchs/bench_binary_op_slabs.s: src/benchs/bench_binary_op_slabs.cu.s
.PHONY : src/benchs/bench_binary_op_slabs.s

# target to generate assembly for a file
src/benchs/bench_binary_op_slabs.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_binary_op_slabs.cu.s
.PHONY : src/benchs/bench_binary_op_slabs.cu.s

src/benchs/bench_compressstore_baseline_cub.o: src/benchs/bench_compressstore_baseline_cub.cu.o
.PHONY : src/benchs/bench_compressstore_baseline_cub.o

# target to build an object file
src/benchs/bench_compressstore_baseline_cub.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_compressstore_baseline_cub.cu.o
.PHONY : src/benchs/bench_compressstore_baseline_cub.cu.o

src/benchs/bench_compressstore_baseline_cub.i: src/benchs/bench_compressstore_baseline_cub.cu.i
.PHONY : src/benchs/bench_compressstore_baseline_cub.i

# target to preprocess a source file
src/benchs/bench_compressstore_baseline_cub.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_compressstore_baseline_cub.cu.i
.PHONY : src/benchs/bench_compressstore_baseline_cub.cu.i

src/benchs/bench_compressstore_baseline_cub.s: src/benchs/bench_compressstore_baseline_cub.cu.s
.PHONY : src/benchs/bench_compressstore_baseline_cub.s

# target to generate assembly for a file
src/benchs/bench_compressstore_baseline_cub.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_compressstore_baseline_cub.cu.s
.PHONY : src/benchs/bench_compressstore_baseline_cub.cu.s

src/benchs/bench_compressstore_slabs.o: src/benchs/bench_compressstore_slabs.cu.o
.PHONY : src/benchs/bench_compressstore_slabs.o

# target to build an object file
src/benchs/bench_compressstore_slabs.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_compressstore_slabs.cu.o
.PHONY : src/benchs/bench_compressstore_slabs.cu.o

src/benchs/bench_compressstore_slabs.i: src/benchs/bench_compressstore_slabs.cu.i
.PHONY : src/benchs/bench_compressstore_slabs.i

# target to preprocess a source file
src/benchs/bench_compressstore_slabs.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_compressstore_slabs.cu.i
.PHONY : src/benchs/bench_compressstore_slabs.cu.i

src/benchs/bench_compressstore_slabs.s: src/benchs/bench_compressstore_slabs.cu.s
.PHONY : src/benchs/bench_compressstore_slabs.s

# target to generate assembly for a file
src/benchs/bench_compressstore_slabs.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_compressstore_slabs.cu.s
.PHONY : src/benchs/bench_compressstore_slabs.cu.s

src/benchs/bench_filter_baseline.o: src/benchs/bench_filter_baseline.cu.o
.PHONY : src/benchs/bench_filter_baseline.o

# target to build an object file
src/benchs/bench_filter_baseline.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_filter_baseline.cu.o
.PHONY : src/benchs/bench_filter_baseline.cu.o

src/benchs/bench_filter_baseline.i: src/benchs/bench_filter_baseline.cu.i
.PHONY : src/benchs/bench_filter_baseline.i

# target to preprocess a source file
src/benchs/bench_filter_baseline.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_filter_baseline.cu.i
.PHONY : src/benchs/bench_filter_baseline.cu.i

src/benchs/bench_filter_baseline.s: src/benchs/bench_filter_baseline.cu.s
.PHONY : src/benchs/bench_filter_baseline.s

# target to generate assembly for a file
src/benchs/bench_filter_baseline.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_filter_baseline.cu.s
.PHONY : src/benchs/bench_filter_baseline.cu.s

src/benchs/bench_filter_nogaps.o: src/benchs/bench_filter_nogaps.cu.o
.PHONY : src/benchs/bench_filter_nogaps.o

# target to build an object file
src/benchs/bench_filter_nogaps.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_filter_nogaps.cu.o
.PHONY : src/benchs/bench_filter_nogaps.cu.o

src/benchs/bench_filter_nogaps.i: src/benchs/bench_filter_nogaps.cu.i
.PHONY : src/benchs/bench_filter_nogaps.i

# target to preprocess a source file
src/benchs/bench_filter_nogaps.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_filter_nogaps.cu.i
.PHONY : src/benchs/bench_filter_nogaps.cu.i

src/benchs/bench_filter_nogaps.s: src/benchs/bench_filter_nogaps.cu.s
.PHONY : src/benchs/bench_filter_nogaps.s

# target to generate assembly for a file
src/benchs/bench_filter_nogaps.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_filter_nogaps.cu.s
.PHONY : src/benchs/bench_filter_nogaps.cu.s

src/benchs/bench_filter_slabs.o: src/benchs/bench_filter_slabs.cu.o
.PHONY : src/benchs/bench_filter_slabs.o

# target to build an object file
src/benchs/bench_filter_slabs.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_filter_slabs.cu.o
.PHONY : src/benchs/bench_filter_slabs.cu.o

src/benchs/bench_filter_slabs.i: src/benchs/bench_filter_slabs.cu.i
.PHONY : src/benchs/bench_filter_slabs.i

# target to preprocess a source file
src/benchs/bench_filter_slabs.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_filter_slabs.cu.i
.PHONY : src/benchs/bench_filter_slabs.cu.i

src/benchs/bench_filter_slabs.s: src/benchs/bench_filter_slabs.cu.s
.PHONY : src/benchs/bench_filter_slabs.s

# target to generate assembly for a file
src/benchs/bench_filter_slabs.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_filter_slabs.cu.s
.PHONY : src/benchs/bench_filter_slabs.cu.s

src/benchs/bench_groupby_sm_array.o: src/benchs/bench_groupby_sm_array.cu.o
.PHONY : src/benchs/bench_groupby_sm_array.o

# target to build an object file
src/benchs/bench_groupby_sm_array.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_groupby_sm_array.cu.o
.PHONY : src/benchs/bench_groupby_sm_array.cu.o

src/benchs/bench_groupby_sm_array.i: src/benchs/bench_groupby_sm_array.cu.i
.PHONY : src/benchs/bench_groupby_sm_array.i

# target to preprocess a source file
src/benchs/bench_groupby_sm_array.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_groupby_sm_array.cu.i
.PHONY : src/benchs/bench_groupby_sm_array.cu.i

src/benchs/bench_groupby_sm_array.s: src/benchs/bench_groupby_sm_array.cu.s
.PHONY : src/benchs/bench_groupby_sm_array.s

# target to generate assembly for a file
src/benchs/bench_groupby_sm_array.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_groupby_sm_array.cu.s
.PHONY : src/benchs/bench_groupby_sm_array.cu.s

src/benchs/bench_groupby_sort_cub.o: src/benchs/bench_groupby_sort_cub.cu.o
.PHONY : src/benchs/bench_groupby_sort_cub.o

# target to build an object file
src/benchs/bench_groupby_sort_cub.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_groupby_sort_cub.cu.o
.PHONY : src/benchs/bench_groupby_sort_cub.cu.o

src/benchs/bench_groupby_sort_cub.i: src/benchs/bench_groupby_sort_cub.cu.i
.PHONY : src/benchs/bench_groupby_sort_cub.i

# target to preprocess a source file
src/benchs/bench_groupby_sort_cub.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_groupby_sort_cub.cu.i
.PHONY : src/benchs/bench_groupby_sort_cub.cu.i

src/benchs/bench_groupby_sort_cub.s: src/benchs/bench_groupby_sort_cub.cu.s
.PHONY : src/benchs/bench_groupby_sort_cub.s

# target to generate assembly for a file
src/benchs/bench_groupby_sort_cub.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_groupby_sort_cub.cu.s
.PHONY : src/benchs/bench_groupby_sort_cub.cu.s

src/benchs/bench_hop_baseline_cub.o: src/benchs/bench_hop_baseline_cub.cu.o
.PHONY : src/benchs/bench_hop_baseline_cub.o

# target to build an object file
src/benchs/bench_hop_baseline_cub.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_hop_baseline_cub.cu.o
.PHONY : src/benchs/bench_hop_baseline_cub.cu.o

src/benchs/bench_hop_baseline_cub.i: src/benchs/bench_hop_baseline_cub.cu.i
.PHONY : src/benchs/bench_hop_baseline_cub.i

# target to preprocess a source file
src/benchs/bench_hop_baseline_cub.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_hop_baseline_cub.cu.i
.PHONY : src/benchs/bench_hop_baseline_cub.cu.i

src/benchs/bench_hop_baseline_cub.s: src/benchs/bench_hop_baseline_cub.cu.s
.PHONY : src/benchs/bench_hop_baseline_cub.s

# target to generate assembly for a file
src/benchs/bench_hop_baseline_cub.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_hop_baseline_cub.cu.s
.PHONY : src/benchs/bench_hop_baseline_cub.cu.s

src/benchs/bench_hop_nogaps.o: src/benchs/bench_hop_nogaps.cu.o
.PHONY : src/benchs/bench_hop_nogaps.o

# target to build an object file
src/benchs/bench_hop_nogaps.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_hop_nogaps.cu.o
.PHONY : src/benchs/bench_hop_nogaps.cu.o

src/benchs/bench_hop_nogaps.i: src/benchs/bench_hop_nogaps.cu.i
.PHONY : src/benchs/bench_hop_nogaps.i

# target to preprocess a source file
src/benchs/bench_hop_nogaps.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_hop_nogaps.cu.i
.PHONY : src/benchs/bench_hop_nogaps.cu.i

src/benchs/bench_hop_nogaps.s: src/benchs/bench_hop_nogaps.cu.s
.PHONY : src/benchs/bench_hop_nogaps.s

# target to generate assembly for a file
src/benchs/bench_hop_nogaps.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_hop_nogaps.cu.s
.PHONY : src/benchs/bench_hop_nogaps.cu.s

src/benchs/bench_hop_slabs.o: src/benchs/bench_hop_slabs.cu.o
.PHONY : src/benchs/bench_hop_slabs.o

# target to build an object file
src/benchs/bench_hop_slabs.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_hop_slabs.cu.o
.PHONY : src/benchs/bench_hop_slabs.cu.o

src/benchs/bench_hop_slabs.i: src/benchs/bench_hop_slabs.cu.i
.PHONY : src/benchs/bench_hop_slabs.i

# target to preprocess a source file
src/benchs/bench_hop_slabs.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_hop_slabs.cu.i
.PHONY : src/benchs/bench_hop_slabs.cu.i

src/benchs/bench_hop_slabs.s: src/benchs/bench_hop_slabs.cu.s
.PHONY : src/benchs/bench_hop_slabs.s

# target to generate assembly for a file
src/benchs/bench_hop_slabs.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/benchs/bench_hop_slabs.cu.s
.PHONY : src/benchs/bench_hop_slabs.cu.s

src/main.o: src/main.cu.o
.PHONY : src/main.o

# target to build an object file
src/main.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/main.cu.o
.PHONY : src/main.cu.o

src/main.i: src/main.cu.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/main.cu.i
.PHONY : src/main.cu.i

src/main.s: src/main.cu.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gpu_elementstuffing.dir/build.make CMakeFiles/gpu_elementstuffing.dir/src/main.cu.s
.PHONY : src/main.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gpu_elementstuffing"
	@echo "... src/benchs/bench_binary_op_baseline.o"
	@echo "... src/benchs/bench_binary_op_baseline.i"
	@echo "... src/benchs/bench_binary_op_baseline.s"
	@echo "... src/benchs/bench_binary_op_nogaps.o"
	@echo "... src/benchs/bench_binary_op_nogaps.i"
	@echo "... src/benchs/bench_binary_op_nogaps.s"
	@echo "... src/benchs/bench_binary_op_slabs.o"
	@echo "... src/benchs/bench_binary_op_slabs.i"
	@echo "... src/benchs/bench_binary_op_slabs.s"
	@echo "... src/benchs/bench_compressstore_baseline_cub.o"
	@echo "... src/benchs/bench_compressstore_baseline_cub.i"
	@echo "... src/benchs/bench_compressstore_baseline_cub.s"
	@echo "... src/benchs/bench_compressstore_slabs.o"
	@echo "... src/benchs/bench_compressstore_slabs.i"
	@echo "... src/benchs/bench_compressstore_slabs.s"
	@echo "... src/benchs/bench_filter_baseline.o"
	@echo "... src/benchs/bench_filter_baseline.i"
	@echo "... src/benchs/bench_filter_baseline.s"
	@echo "... src/benchs/bench_filter_nogaps.o"
	@echo "... src/benchs/bench_filter_nogaps.i"
	@echo "... src/benchs/bench_filter_nogaps.s"
	@echo "... src/benchs/bench_filter_slabs.o"
	@echo "... src/benchs/bench_filter_slabs.i"
	@echo "... src/benchs/bench_filter_slabs.s"
	@echo "... src/benchs/bench_groupby_sm_array.o"
	@echo "... src/benchs/bench_groupby_sm_array.i"
	@echo "... src/benchs/bench_groupby_sm_array.s"
	@echo "... src/benchs/bench_groupby_sort_cub.o"
	@echo "... src/benchs/bench_groupby_sort_cub.i"
	@echo "... src/benchs/bench_groupby_sort_cub.s"
	@echo "... src/benchs/bench_hop_baseline_cub.o"
	@echo "... src/benchs/bench_hop_baseline_cub.i"
	@echo "... src/benchs/bench_hop_baseline_cub.s"
	@echo "... src/benchs/bench_hop_nogaps.o"
	@echo "... src/benchs/bench_hop_nogaps.i"
	@echo "... src/benchs/bench_hop_nogaps.s"
	@echo "... src/benchs/bench_hop_slabs.o"
	@echo "... src/benchs/bench_hop_slabs.i"
	@echo "... src/benchs/bench_hop_slabs.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

